# Generated by Django 5.2.16 on 2026-07-28 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('mobile', 'Mobile'), ('fax', 'Fax'), ('website', 'Website'), ('social', 'Social profile'), ('messaging', 'Messaging / IM'), ('other', 'Other')], default='email', max_length=16)),
                ('value', models.CharField(help_text='Email address, phone number, URL, or handle.', max_length=320)),
                ('label', models.CharField(blank=True, default='', help_text='Context label, e.g. work, home, billing, LinkedIn.', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-is_primary', 'kind'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_contac_content_6aca38_idx'), models.Index(fields=['kind', 'value'], name='core_contac_kind_d1fd3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('scheme', models.CharField(help_text='Identifier scheme, e.g. DUNS, EIN, LEI, ISBN, GTIN, DOI, SSN, internal.', max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_identi_content_160c54_idx'), models.Index(fields=['scheme', 'value'], name='core_identi_scheme_191198_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'scheme', 'value'), name='uniq_identifier_per_entity')],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_object_id', models.UUIDField()),
                ('predicate', models.CharField(help_text='Relationship type, e.g. relatedTo, partOf, owns, memberOf, supersedes, dependsOn, mentions.', max_length=64)),
                ('object_object_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('subject_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['subject_content_type', 'subject_object_id'], name='core_relati_subject_9bd296_idx'), models.Index(fields=['object_content_type', 'object_object_id'], name='core_relati_object__da8b1e_idx'), models.Index(fields=['predicate'], name='core_relati_predica_bfa7ca_idx')],
            },
        ),
    ]
